{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "\n",
    "from psycopg_pool import ConnectionPool\n",
    "from supabase import create_client"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n",
      "error connecting in 'pool-8': connection is bad: connection to server at \"2600:1f18:2e13:9d12:ba30:fab4:f99d:b481\", port 5432 failed: Network is unreachable\n",
      "\tIs the server running on that host and accepting TCP/IP connections?\n"
     ]
    }
   ],
   "source": [
    "conurl = \"postgresql://postgres:P$rr$s$to@db.mdrkbrzktcwfnqrirpny.supabase.co:5432/postgres\"\n",
    "pool = ConnectionPool(conurl)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "conurl = os.environ.get(\"SUPABASE_URL\")\n",
    "if not conurl:\n",
    "    print(\"Please set the SUPABASE_URL environment variable.\")\n",
    "    sys.exit(1)\n",
    "\n",
    "pool = create_client(conurl, os.environ.get(\"SUPABASE_KEY\"))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "ename": "APIError",
     "evalue": "{'code': '42501', 'details': None, 'hint': None, 'message': 'permission denied for schema financelive'}",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mAPIError\u001b[39m                                  Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[28]\u001b[39m\u001b[32m, line 5\u001b[39m\n\u001b[32m      1\u001b[39m response = (\n\u001b[32m      2\u001b[39m     \u001b[43mpool\u001b[49m\u001b[43m.\u001b[49m\u001b[43mschema\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mfinancelive\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m      3\u001b[39m \u001b[43m    \u001b[49m\u001b[43m.\u001b[49m\u001b[43mtable\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43musers\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m      4\u001b[39m \u001b[43m    \u001b[49m\u001b[43m.\u001b[49m\u001b[43mselect\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43m*\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m----> \u001b[39m\u001b[32m5\u001b[39m \u001b[43m    \u001b[49m\u001b[43m.\u001b[49m\u001b[43mexecute\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m      6\u001b[39m )\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/Desktop/LovableHackaton/lovablevenv/lib/python3.12/site-packages/postgrest/_sync/request_builder.py:78\u001b[39m, in \u001b[36mSyncQueryRequestBuilder.execute\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m     76\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m APIResponse[_ReturnT].from_http_request_response(r)\n\u001b[32m     77\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m---> \u001b[39m\u001b[32m78\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m APIError(r.json())\n\u001b[32m     79\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m ValidationError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m     80\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m APIError(r.json()) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01me\u001b[39;00m\n",
      "\u001b[31mAPIError\u001b[39m: {'code': '42501', 'details': None, 'hint': None, 'message': 'permission denied for schema financelive'}"
     ]
    }
   ],
   "source": [
    "response = (\n",
    "    pool.schema(\"financelive\")\n",
    "    .table(\"users\")\n",
    "    .select(\"*\")\n",
    "    .execute()\n",
    ")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from anthropic import Client\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "lovablevenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
